name: qty
description: Quantities representation and unit conversions. Defines most common units for several physical properties such as Mass, Length, Volume and Time.
homepage: https://github.com/cc-nogueira/qty

version: 0.9.1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  equatable: ^2.0.3

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.2
