name: qty
description: Quantities representation and unit conversions. Defines most common units for several physical properties such as Mass, Length, Volume and Time.
version: 0.1.3
homepage: https://github.com/ricardo-nogueira-cc/qty

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.5
