name: qty
description: Quantities representation and unit conversions. Defines most common units for several physical properties such as Mass, Length, Volume and Time.
version: 0.1.4
homepage: https://github.com/cc-nogueira/qty

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.5
