name: qty
description: Quantities and Units calculations and conversions. Defines most common units for several PhysicalProperties such as Mass, Length, Volume, all organized inside SystemOfUnits like InternationalSystemOfUnits, ImperialSystemOfUnits and NauticalSystemOfUnits.
version: 0.1.2
homepage: https://github.com/ricardo-nogueira-cc/qty

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.5
